import os
import re
import matplotlib.pyplot as plt
from matplotlib import rc
import numpy as np

a = []
b = []

print('Projeto Visualização de Dados 0.1')
print('')
# Parseia os dados do arquivo teste.txt
for line in open('/home/ryukahtk/teste.txt', 'r'):
    a.append(re.findall(r"[\S']+", line)[0])
    b.append(re.findall(r"[\S']+", line)[5])

menu = input('Selecione o nivel da classificação:')
if menu == '1':
    labels = ['Sample 1']
    classified = float(a[1])
    unclassified = float(a[0])
    width = 2.0       # the width of the bars: can also be len(x) sequence

    fig, ax = plt.subplots()

    ax.bar(labels, classified, width, label=str(b[1]), color=['green'])
    ax.bar(labels, unclassified, width, label=str(b[0]), color=['blue'])

    ax.set_ylabel('Signifiance')
    ax.set_title('Sample 1')
    ax.legend()

    plt.show()

elif menu == '2':
    labels = ['Sample 1']
    proteo = float(a[4])
    actino = float(a[228])
    firmic = float(a[283])
    chrolo = float(a[326])
    teneri = float(a[335])
    bacteriori = float(a[346])
    gemma = float(a[397])
    acidob = float(a[405])
    nitros = float(a[432])
    defferi = float(a[437])
    width = 2.0

    fig, ax = plt.subplots()

    ax.bar(labels, proteo, width, label='Proteobacteria', color=['green'])
    ax.bar(labels, actino, width, label='Actinobacteria', color=['blue'])
    ax.bar(labels, firmic, width, label='Firmicutes', color=['yellow'])
    ax.bar(labels, chrolo, width, label='Chloroflexi', color=['orange'])
    ax.bar(labels, teneri, width, label='Tenericutes', color=['black'])
    ax.bar(labels, bacteriori, width, label='Bacteroidetes', color=['pink'])
    ax.bar(labels, gemma, width, label='Gemmatimonadetes', color=['gray'])
    ax.bar(labels, acidob, width, label='Acidobacteria', color=['red'])
    ax.bar(labels, nitros, width, label='Nitrospirae', color=['purple'])
    ax.bar(labels, defferi, width, label='Deferribacteres', color=['blue'])
    ax.set_ylabel('Signifiance')
    ax.set_title('Sample 1')
    ax.legend()

    plt.show()

elif menu == '3':
    labels = ['Sample 1']
    alpha = float(a[5])
    delta = float(a[93])
    epsilon = float(a[142])
    beta = float(a[145])
    gamma = float(a[184])
    oligo = float(a[217])
    acidith = float(a[223])
    actino2 = float(a[228])
    thermo = float(a[262])
    acidimi = float(a[268])
    rubro = float(a[274])
    corio = float(a[280])
    clost = float(a[284])
    bacil = float(a[304])
    erysi = float(a[317])
    negati = float(a[322])
    anaero = float(a[327])
    chrolo2 = float(a[330])
    molli = float(a[336])
    chitino = float(a[347])
    flavo = float(a[363])
    cytopha = float(a[382])
    sphingo = float(a[387])
    sapro = float(a[391])
    gemmati2 = float(a[398])
    solibac = float(a[406])
    acidob2 = float(a[412])
    blast = float(a[428])
    nitros = float(a[433])
    defer2 = float(a[439])
    width = 2.0

    fig, ax = plt.subplots()

    ax.bar(labels, alpha, width, label='Alphaproteobacteria', color=['green'])
    ax.bar(labels, delta, width, label='Deltaproteobacteria', color=['blue'])
    ax.bar(labels, epsilon, width, label='Epsilonproteobacteria', color=['yellow'])
    ax.bar(labels, beta, width, label='Betaproteobacteria', color=['orange'])
    ax.bar(labels, gamma, width, label='Gammaproteobacteria', color=['black'])
    ax.bar(labels, oligo, width, label='Oligoflexia', color=['pink'])
    ax.bar(labels, acidith, width, label='Acidithiobacillia', color=['gray'])
    ax.bar(labels, actino2, width, label='Actinobacteria', color=['red'])
    ax.bar(labels, thermo, width, label='Thermoleophilia', color=['purple'])
    ax.bar(labels, acidimi, width, label='Acidimicrobiia', color=['blue'])
    ax.bar(labels, rubro, width, label='Rubrobacteria', color=['green'])
    ax.bar(labels, corio, width, label='Coriobacteriia', color=['blue'])
    ax.bar(labels, clost, width, label='Clostridia', color=['yellow'])
    ax.bar(labels, bacil, width, label='Bacilli', color=['orange'])
    ax.bar(labels, erysi, width, label='Erysipelotrichia', color=['black'])
    ax.bar(labels, negati, width, label='Negativicutes', color=['pink'])
    ax.bar(labels, anaero, width, label='Anaerolineae', color=['gray'])
    ax.bar(labels, chrolo2, width, label='Chloroflexia', color=['red'])
    ax.bar(labels, molli, width, label='Mollicutes', color=['purple'])
    ax.bar(labels, chitino, width, label='Chitinophagia', color=['blue'])
    ax.bar(labels, flavo, width, label='Flavobacteriia', color=['green'])
    ax.bar(labels, cytopha, width, label='Cytophagia', color=['blue'])
    ax.bar(labels, sphingo, width, label='Sphingobacteriia', color=['yellow'])
    ax.bar(labels, sapro, width, label='Saprospiria', color=['orange'])
    ax.bar(labels, gemmati2, width, label='Gemmatimonadetes', color=['gray'])
    ax.bar(labels, solibac, width, label='Solibacteres', color=['red'])
    ax.bar(labels, acidob2, width, label='Acidobacteriia', color=['purple'])
    ax.bar(labels, blast, width, label='Blastocatellia', color=['blue'])
    ax.bar(labels, nitros, width, label='Nitrospira', color=['green'])
    ax.bar(labels, defer2, width, label='Deferribacteres', color=['blue'])

    ax.set_ylabel('Signifiance')
    ax.set_title('Sample 1')
    ax.legend()

    plt.show()

elif menu == '4':
    labels = ['Sample 1']
    rhizo = float(a[6])
    rhodo = float(a[56])
    sphingo2 = float(a[71])
    caulobac = float(a[81])
    rhodo2 = float(a[88])
    myxococ = float(a[94])
    desulfuromonadales = float(a[117])
    desulfubacterales = float(a[120])
    syntrophobac = float(a[132])
    desulfarculates = float(a[137])
    campylobact = float(a[143])
    burkholderial = float(a[149])
    nitrosomona = float(a[172])
    xantho = float(a[185])
    nevskiales = float(a[194])
    oceanospi = float(a[198])
    pseudomonadales = float(a[201])
    cellvibrio = float(a[204])
    thiotricha = float(a[208])
    enterobact = float(a[213])
    bdellovibrio = float(a[218])
    acidithobacilalles = float(a[224])
    propionibacter = float(a[230])
    micrococcales = float(a[237])
    micromonos = float(a[243])
    nakamure = float(a[245])
    corynebac = float(a[251])
    pseudomono = float(a[254])
    streptomyceta = float(a[259])
    solirubro = float(a[263])
    acidimicrobiales = float(a[269])
    rubrobacterales = float(a[275])
    coribacteriales = float(a[281])
    clostridiales = float(a[285])
    bacilalles = float(a[305])
    lactobacilalles = float(a[313])
    erysipelotrichales = float(a[318])
    selemonodales = float(a[323])
    anaerolinedales = float(a[328])
    chroloflexales = float(a[331])
    mycoplasma = float(a[337])
    chitinophagales = float(a[348])
    flavobacteriales = float(a[364])
    bacteriodet = float(a[376])
    cytophagales = float(a[383])
    sphingobacteriales = float(a[388])
    saprospirales = float(a[392])
    gemmatimonadales = float(a[399])
    solibacterales = float(a[407])
    acidobacterales = float(a[413])
    nitrospirales = float(a[434])
    deferribacterales = float(a[439])
    width = 2.0

    fig, ax = plt.subplots()

    ax.bar(labels, rhizo, width, label='Rhizobiales', color=['green'])
    ax.bar(labels, rhodo2, width, label='Rhodospirillales', color=['blue'])
    ax.bar(labels, sphingo2, width, label='Sphingomonadales', color=['yellow'])
    ax.bar(labels, caulobac, width, label='Caulobacterales', color=['orange'])
    ax.bar(labels, rhodo2, width, label='Rhodobacterales', color=['black'])
    ax.bar(labels, myxococ, width, label='Myxococcales', color=['pink'])
    ax.bar(labels, desulfuromonadales, width, label='Desulfuromonadales', color=['gray'])
    ax.bar(labels, desulfubacterales, width, label='Desulfobacterales', color=['red'])
    ax.bar(labels, syntrophobac, width, label='Syntrophobacterales', color=['purple'])
    ax.bar(labels, desulfarculates, width, label='Desulfarculales', color=['blue'])
    ax.bar(labels, campylobact, width, label='Campylobacterales', color=['green'])
    ax.bar(labels, burkholderial, width, label='Burkholderiales', color=['blue'])
    ax.bar(labels, nitrosomona, width, label='Nitrosomonadales', color=['yellow'])
    ax.bar(labels, xantho, width, label='Xanthomonadales', color=['orange'])
    ax.bar(labels, nevskiales, width, label='Nevskiales', color=['black'])
    ax.bar(labels, oceanospi, width, label='Oceanospirillales', color=['pink'])
    ax.bar(labels, pseudomonadales, width, label='Pseudomonadales', color=['gray'])
    ax.bar(labels, cellvibrio, width, label='Cellvibrionales', color=['red'])
    ax.bar(labels, thiotricha, width, label='Thiotrichales', color=['purple'])
    ax.bar(labels, enterobact, width, label='Enterobacterales', color=['blue'])
    ax.bar(labels, bdellovibrio, width, label='Bdellovibrionales', color=['green'])
    ax.bar(labels, acidithobacilalles, width, label='Acidithiobacillales', color=['blue'])
    ax.bar(labels, propionibacter, width, label='Propionibacteriales', color=['yellow'])
    ax.bar(labels, micrococcales, width, label='Micrococcales', color=['orange'])
    ax.bar(labels, micromonos, width, label='Micromonosporales', color=['gray'])
    ax.bar(labels, nakamure, width, label='Nakamurellales', color=['red'])
    ax.bar(labels, corynebac, width, label='Corynebacteriales', color=['purple'])
    ax.bar(labels, pseudomono, width, label='Pseudonocardiales', color=['blue'])
    ax.bar(labels, streptomyceta, width, label='Streptomycetales', color=['green'])
    ax.bar(labels, solibacterales, width, label='Solirubrobacterales', color=['blue'])
    ax.bar(labels, acidimicrobiales, width, label='Acidimicrobiales', color=['blue'])
    ax.bar(labels, rubrobacterales, width, label='Rubrobacterales', color=['green'])
    ax.bar(labels, coribacteriales, width, label='Coriobacteriales', color=['blue'])
    ax.bar(labels, clostridiales, width, label='Clostridiales', color=['yellow'])
    ax.bar(labels, bacilalles, width, label='Bacillales', color=['orange'])
    ax.bar(labels, lactobacilalles, width, label='Lactobacillales', color=['black'])
    ax.bar(labels, erysipelotrichales, width, label='Erysipelotrichales', color=['pink'])
    ax.bar(labels, selemonodales, width, label='Selenomonadales', color=['gray'])
    ax.bar(labels, anaerolinedales, width, label='Anaerolineales', color=['red'])
    ax.bar(labels, chroloflexales, width, label='Chloroflexales', color=['purple'])
    ax.bar(labels, mycoplasma, width, label='Mycoplasmatales', color=['blue'])
    ax.bar(labels, chitinophagales, width, label='Chitinophagales', color=['green'])
    ax.bar(labels, flavobacteriales, width, label='Flavobacteriales', color=['blue'])
    ax.bar(labels, bacteriodet, width, label='Bacteroidetes Order II. Incertae sedis', color=['yellow'])
    ax.bar(labels, cytophagales, width, label='Cytophagales', color=['orange'])
    ax.bar(labels, sphingobacteriales, width, label='Sphingobacteriales', color=['gray'])
    ax.bar(labels, saprospirales, width, label='Saprospirales', color=['red'])
    ax.bar(labels, gemmatimonadales, width, label='Gemmatimonadales', color=['purple'])
    ax.bar(labels, solibacterales, width, label='Solibacterales', color=['blue'])
    ax.bar(labels, acidobacterales, width, label='Acidobacteriales', color=['green'])
    ax.bar(labels, nitrospirales, width, label='Nitrospirales', color=['blue'])
    ax.bar(labels, deferribacterales, width, label='Deferribacterales', color=['purple'])
    ax.set_ylabel('Signifiance')
    ax.set_title('Sample 1')
    ax.legend()

    plt.show()

elif menu == '5':
    labels = ['Sample 1']
    bradyrhizo = float(a[7])
    hyphomicro = float(a[13])
    phyllobacter = float(a[26])
    xanthobacter = float(a[36])
    rhizobiac = float(a[43])
    beijerinck = float(a[47])
    methylo = float(a[52])
    chelatoco = float(a[54])
    acetobacter = float(a[57])
    rhodospirill = float(a[60])
    sphingomona = float(a[72])
    erythobacter = float(a[79])
    caulobacter = float(a[82])
    rhodobacter = float(a[89])
    polyangi = float(a[96])
    sandarci = float(a[101])
    archagi = float(a[105])
    anaeromy = float(a[108])
    myxococea = float(a[110])
    koflerri = float(a[113])
    geobacter = float(a[118])
    desulfobacter = float(a[121])
    desulfobaceae = float(a[128])
    syntrophaceae = float(a[133])
    desulfarculaceae = float(a[138])
    helicobacter = float(a[144])
    comamonada = float(a[162])
    burkholderiaceae = float(a[170])
    sterolibacter = float(a[173])
    nitrosomonadaceae = float(a[177])
    xanthomonadaceae = float(a[186])
    rhodanobacter = float(a[190])
    sinobacter = float(a[195])
    halomona = float(a[199])
    pseudomonadace = float(a[202])
    haliece = float(a[205])
    francisel = float(a[209])
    erwini = float(a[214])
    bdllovibrinaceae = float(a[219])
    acidithceace = float(a[225])
    nocardioid = float(a[231])
    microbacter = float(a[238])
    micrococaeae = float(a[241])
    cellulomonada = float(a[242])
    micromonosporadeceae = float(a[244])
    nakamurellaceae = float(a[246])
    mycobactericeae = float(a[252])
    pseudocardia = float(a[255])
    streptomycetaceae = float(a[260])
    conexibacteraceae = float(a[264])
    acidimicrobicae = float(a[270])
    rubrobacterceae = float(a[276])
    atopobiaceae = float(a[282])
    clostridicae = float(a[293])
    peptococcae = float(a[300])
    syntrophoma = float(a[306])
    bacillaceae = float(a[308])
    paenibacilla = float(a[310])
    alicyclobacilla = float(a[314])
    carnobacteriaceae = float(a[319])
    erysipelotrichace = float(a[324])
    selemononada = float(a[329])
    anaerolineaceae = float(a[333])
    roseiflexace = float(a[349])
    mycoplasmataceae = float(a[365])
    chitinophagaceae = float(a[377])
    flavobactercae = float(a[384])
    rhodothermaceae = float(a[389])
    hymenobactercae = float(a[393])
    sphingobactercae = float(a[400])
    haliscomonobacter = float(a[408])
    gemmatimonadacae = float(a[414])
    solibactercae = float(a[435])
    acidobactercea = float(a[440])
    nitrospriracea = float(a[435])
    defferibactercae = float(a[440])
    width = 2.0

    fig, ax = plt.subplots()

    ax.bar(labels, bradyrhizo, width, label='Bradyrhizobiaceae', color=['green'])
    ax.bar(labels, hyphomicro, width, label='Hyphomicrobiaceae', color=['blue'])
    ax.bar(labels, phyllobacter, width, label='Phyllobacteriaceae', color=['yellow'])
    ax.bar(labels, xanthobacter, width, label='Xanthobacteraceae', color=['orange'])
    ax.bar(labels, rhizobiac, width, label='Rhizobiaceae', color=['black'])
    ax.bar(labels, beijerinck, width, label='Beijerinckiaceae', color=['pink'])
    ax.bar(labels, methylo, width, label='Methylobacteriaceae', color=['gray'])
    ax.bar(labels, chelatoco, width, label='Chelatococcaceae', color=['red'])
    ax.bar(labels, acetobacter, width, label='Acetobacteraceae', color=['purple'])
    ax.bar(labels, rhodospirill, width, label='Rhodospirillaceae', color=['blue'])
    ax.bar(labels, sphingobactercae, width, label='Sphingomonadaceae', color=['green'])
    ax.bar(labels, erythobacter, width, label='Erythrobacteraceae', color=['blue'])
    ax.bar(labels, caulobacter, width, label='Caulobacteraceae', color=['yellow'])
    ax.bar(labels, rhodobacter, width, label='Rhodobacteraceae', color=['orange'])
    ax.bar(labels, polyangi, width, label='Polyangiaceae', color=['black'])
    ax.bar(labels, sandarci, width, label='Sandaracinaceae', color=['pink'])
    ax.bar(labels, archagi, width, label='Archangiaceae', color=['gray'])
    ax.bar(labels, anaeromy, width, label='Anaeromyxobacteraceae', color=['red'])
    ax.bar(labels, myxococea, width, label='Myxococcaceae', color=['purple'])
    ax.bar(labels, koflerri, width, label='Kofleriaceae', color=['blue'])
    ax.bar(labels, geobacter, width, label='Geobacteraceae', color=['green'])
    ax.bar(labels, desulfobacter, width, label='Desulfobacteraceae', color=['blue'])
    ax.bar(labels, desulfobaceae, width, label='Desulfobulbaceae', color=['yellow'])
    ax.bar(labels, syntrophaceae, width, label='Syntrophaceae', color=['orange'])
    ax.bar(labels, desulfobaceae, width, label='Desulfarculaceae', color=['gray'])
    ax.bar(labels, helicobacter, width, label='Helicobacteraceae', color=['red'])
    ax.bar(labels, comamonada, width, label='Comamonadaceae', color=['purple'])
    ax.bar(labels, burkholderiaceae, width, label='Burkholderiaceae', color=['blue'])
    ax.bar(labels, sterolibacter, width, label='Sterolibacteriaceae', color=['green'])
    ax.bar(labels, nitrosomonadaceae, width, label='Nitrosomonadaceae', color=['blue'])
    ax.bar(labels, xanthomonadaceae, width, label='Xanthomonadaceae', color=['blue'])
    ax.bar(labels, rhodanobacter, width, label='Rhodanobacteraceae', color=['green'])
    ax.bar(labels, sinobacter, width, label='Sinobacteraceae', color=['blue'])
    ax.bar(labels, halomona, width, label='Halomonadaceae', color=['yellow'])
    ax.bar(labels, pseudomonadace, width, label='Pseudomonadaceae', color=['orange'])
    ax.bar(labels, haliece, width, label='Halieaceae', color=['black'])
    ax.bar(labels, francisel, width, label='Francisellaceae', color=['pink'])
    ax.bar(labels, erwini, width, label='Erwiniaceae', color=['gray'])
    ax.bar(labels, bdllovibrinaceae, width, label='Bdellovibrionaceae', color=['red'])
    ax.bar(labels, acidithceace, width, label='Acidithiobacillaceae', color=['purple'])
    ax.bar(labels, nocardioid, width, label='Nocardioidaceae', color=['blue'])
    ax.bar(labels, microbacter, width, label='Microbacteriaceae', color=['green'])
    ax.bar(labels, micrococaeae, width, label='Micrococcaceae', color=['blue'])
    ax.bar(labels, cellulomonada, width, label='Cellulomonadaceae', color=['yellow'])
    ax.bar(labels, micromonosporadeceae, width, label='Micromonosporaceae', color=['orange'])
    ax.bar(labels, nakamurellaceae, width, label='Nakamurellaceae', color=['gray'])
    ax.bar(labels, mycobactericeae, width, label='Mycobacteriaceae', color=['red'])
    ax.bar(labels, pseudocardia, width, label='Pseudonocardiaceae', color=['purple'])
    ax.bar(labels, streptomycetaceae, width, label='Streptomycetaceae', color=['blue'])
    ax.bar(labels, conexibacteraceae, width, label='Conexibacteraceae', color=['green'])
    ax.bar(labels, acidimicrobicae, width, label='Acidimicrobiaceae', color=['blue'])
    ax.bar(labels, rubrobacterceae, width, label='Rubrobacteraceae', color=['purple'])
    ax.bar(labels, atopobiaceae, width, label='Atopobiaceae', color=['blue'])
    ax.bar(labels, clostridicae, width, label='Clostridiaceae', color=['green'])
    ax.bar(labels, peptococcae, width, label='Peptococcaceae', color=['blue'])
    ax.bar(labels, syntrophaceae, width, label='Syntrophomonadaceae', color=['yellow'])
    ax.bar(labels, bacillaceae, width, label='Bacillaceae', color=['orange'])
    ax.bar(labels, paenibacilla, width, label='Paenibacillaceae', color=['black'])
    ax.bar(labels, alicyclobacilla, width, label='Alicyclobacillaceae', color=['pink'])
    ax.bar(labels, carnobacteriaceae, width, label='Carnobacteriaceae', color=['gray'])
    ax.bar(labels, erysipelotrichace, width, label='Erysipelotrichaceae', color=['red'])
    ax.bar(labels, selemononada, width, label='Selenomonadaceae', color=['purple'])
    ax.bar(labels, anaerolineaceae, width, label='Anaerolineaceae', color=['blue'])
    ax.bar(labels, roseiflexace, width, label='Roseiflexaceae', color=['green'])
    ax.bar(labels, mycoplasmataceae, width, label='Mycoplasmataceae', color=['blue'])
    ax.bar(labels, chitinophagaceae, width, label='Chitinophagaceae', color=['yellow'])
    ax.bar(labels, flavobactercae, width, label='Flavobacteriaceae', color=['orange'])
    ax.bar(labels, rhodothermaceae, width, label='Rhodothermaceae', color=['gray'])
    ax.bar(labels, hymenobactercae, width, label='Hymenobacteraceae', color=['red'])
    ax.bar(labels, sphingobactercae, width, label='Sphingobacteriaceae', color=['purple'])
    ax.bar(labels, haliscomonobacter, width, label='Haliscomenobacteraceae', color=['blue'])
    ax.bar(labels, gemmatimonadacae, width, label='Gemmatimonadaceae', color=['green'])
    ax.bar(labels, solibactercae, width, label='Solibacteraceae', color=['blue'])
    ax.bar(labels, acidobactercea, width, label='Acidobacteriaceae', color=['purple'])
    ax.bar(labels, nitrospriracea, width, label='Nitrospiraceae', color=['blue'])
    ax.bar(labels, defferibactercae, width, label='Deferribacteraceae', color=['red'])

    ax.set_ylabel('Signifiance')
    ax.set_title('Sample 1')
    ax.legend()

    plt.show()

elif menu == '6':
    labels = ['Sample 1']
    g8 = float(a[8])
    g11 = float(a[11])
    g14 = float(a[14])
    g17 = float(a[17])
    g19 = float(a[19])
    g22 = float(a[22])
    g24 = float(a[24])
    g27 = float(a[27])
    g29 = float(a[29])
    g32 = float(a[32])
    g34 = float(a[34])
    g37 = float(a[37])
    g40 = float(a[40])
    g44 = float(a[44])
    g48 = float(a[48])
    g53 = float(a[53])
    g55 = float(a[55])
    g58 = float(a[58])
    g59 = float(a[59])
    g61 = float(a[61])
    g65 = float(a[65])
    g68 = float(a[68])
    g73 = float(a[73])
    g75 = float(a[75])
    g77 = float(a[77])
    g78 = float(a[78])
    g80 = float(a[80])
    g83 = float(a[83])
    g85 = float(a[85])
    g90 = float(a[90])
    g97 = float(a[97])
    g99 = float(a[99])
    g102 = float(a[102])
    g106 = float(a[106])
    g109 = float(a[109])
    g111 = float(a[111])
    g114 = float(a[114])
    g119 = float(a[119])
    g122 = float(a[122])
    g125 = float(a[125])
    g129 = float(a[129])
    g134 = float(a[134])
    g139 = float(a[139])
    g145 = float(a[145])
    g152 = float(a[152])
    g155 = float(a[155])
    g158 = float(a[158])
    g160 = float(a[160])
    g163 = float(a[163])
    g166 = float(a[166])
    g168 = float(a[168])
    g171 = float(a[171])
    g174 = float(a[174])
    g178 = float(a[178])
    g187 = float(a[187])
    g191 = float(a[191])
    g196 = float(a[196])
    g200 = float(a[200])
    g203 = float(a[203])
    g206 = float(a[206])
    g211 = float(a[210])
    g215 = float(a[215])
    g220 = float(a[220])
    g226 = float(a[226])
    g232 = float(a[232])
    g247 = float(a[247])
    g253 = float(a[253])
    g256 = float(a[256])
    g261 = float(a[261])
    g271 = float(a[271])
    g277 = float(a[277])
    g287 = float(a[287])
    g290 = float(a[290])
    g294 = float(a[294])
    g298 = float(a[298])
    g301 = float(a[301])
    g307 = float(a[307])
    g309 = float(a[309])
    g311 = float(a[311])
    g315 = float(a[315])
    g320 = float(a[320])
    g325 = float(a[325])
    g334 = float(a[334])
    g339 = float(a[339])
    g341 = float(a[341])
    g350 = float(a[350])
    g352 = float(a[352])
    g356 = float(a[356])
    g358 = float(a[358])
    g360 = float(a[360])
    g366 = float(a[366])
    g368 = float(a[368])
    g370 = float(a[370])
    g374 = float(a[374])
    g378 = float(a[378])
    g385 = float(a[385])
    g390 = float(a[390])
    g394 = float(a[394])
    g401 = float(a[401])
    g409 = float(a[409])
    g415 = float(a[415])
    g418 = float(a[418])
    g422 = float(a[422])
    g425 = float(a[425])
    g429 = float(a[429])
    g436 = float(a[436])
    g441 = float(a[441])
    width = 2.0

    fig, ax = plt.subplots()

    ax.bar(labels, g8, width, label=str(b[8]), color=['green'])
    ax.bar(labels, g11, width, label=str(b[11]), color=['blue'])
    ax.bar(labels, g14, width, label=str(b[14]), color=['yellow'])
    ax.bar(labels, g17, width, label=str(b[17]), color=['orange'])
    ax.bar(labels, g19, width, label=str(b[19]), color=['black'])
    ax.bar(labels, g22, width, label=str(b[22]), color=['pink'])
    ax.bar(labels, g24, width, label=str(b[24]), color=['gray'])
    ax.bar(labels, g27, width, label=str(b[27]), color=['red'])
    ax.bar(labels, g29, width, label=str(b[29]), color=['purple'])
    ax.bar(labels, g32, width, label=str(b[32]), color=['blue'])
    ax.set_ylabel('Signifiance')
    ax.set_title('Sample 1')
    ax.legend()

    plt.show()

else:
    print('Opção invalida')
