import re
import matplotlib.pyplot as plt
from matplotlib import rc
import numpy as np

print('Algoritmo Iniciado.')
print('')

# Parseia os dados do arquivo teste.txt


def Main(a, b, fileinput):
    for line in open(fileinput, 'r'):
        a.append(re.findall(r"[\S']+", line)[0])
        b.append(re.findall(r"[\S']+", line)[5])

    menu = input('Selecione o nivel da classificação:')
    if menu == '1':
        labels = ['Sample 1']
        u1 = float(a[1])
        u0 = float(a[0])
        width = 2.0

        fig, ax = plt.subplots()

        ax.bar(labels, u1, width, label=str(b[1]), color=['green'])
        ax.bar(labels, u0, width, label=str(b[0]), color=['blue'])

        ax.set_ylabel('Signifiance')
        ax.set_title('Sample 1')
        ax.legend()

        plt.show()

    # Novo metodo de preencher as variaveis, apenas é necessário as posicionar bem

    elif menu == '2':
        labels = ['Sample 1']
        d4 = float(a[4])
        d228 = float(a[228])
        d283 = float(a[283])
        d326 = float(a[326])
        d335 = float(a[335])
        d346 = float(a[346])
        d397 = float(a[397])
        d405 = float(a[405])
        d432 = float(a[432])
        d437 = float(a[437])
        width = 2.0

        fig, ax = plt.subplots()

        ax.bar(labels, d4, width, label=str(b[8]), color=['green'])
        ax.bar(labels, d228, width, label=str(b[228]), color=['blue'])
        ax.bar(labels, d283, width, label=str(b[283]), color=['yellow'])
        ax.bar(labels, d326, width, label=str(b[326]), color=['orange'])
        ax.bar(labels, d335, width, label=str(b[335]), color=['black'])
        ax.bar(labels, d346, width, label=str(b[346]), color=['pink'])
        ax.bar(labels, d397, width, label=str(b[397]), color=['gray'])
        ax.bar(labels, d405, width, label=str(b[405]), color=['red'])
        ax.bar(labels, d432, width, label=str(b[432]), color=['purple'])
        ax.bar(labels, d437, width, label=str(b[437]), color=['blue'])
        ax.set_ylabel('Signifiance')
        ax.set_title('Sample 1')
        ax.legend()

        plt.show()
    # Nesse momento eu ainda estava utilizando a maneira antiga de botar as variaveis, ocupava muito mais tempo
    elif menu == '3':
        labels = ['Sample 1']
        alpha = float(a[5])
        delta = float(a[93])
        epsilon = float(a[142])
        beta = float(a[145])
        gamma = float(a[184])
        oligo = float(a[217])
        acidith = float(a[223])
        actino2 = float(a[228])
        thermo = float(a[262])
        acidimi = float(a[268])
        rubro = float(a[274])
        corio = float(a[280])
        clost = float(a[284])
        bacil = float(a[304])
        erysi = float(a[317])
        negati = float(a[322])
        anaero = float(a[327])
        chrolo2 = float(a[330])
        molli = float(a[336])
        chitino = float(a[347])
        flavo = float(a[363])
        cytopha = float(a[382])
        sphingo = float(a[387])
        sapro = float(a[391])
        gemmati2 = float(a[398])
        solibac = float(a[406])
        acidob2 = float(a[412])
        blast = float(a[428])
        nitros = float(a[433])
        defer2 = float(a[439])
        width = 2.0

        fig, ax = plt.subplots()

        ax.bar(labels, alpha, width, label='Alphaproteobacteria', color=['green'])
        ax.bar(labels, delta, width, label='Deltaproteobacteria', color=['blue'])
        ax.bar(labels, epsilon, width, label='Epsilonproteobacteria', color=['yellow'])
        ax.bar(labels, beta, width, label='Betaproteobacteria', color=['orange'])
        ax.bar(labels, gamma, width, label='Gammaproteobacteria', color=['black'])
        ax.bar(labels, oligo, width, label='Oligoflexia', color=['pink'])
        ax.bar(labels, acidith, width, label='Acidithiobacillia', color=['gray'])
        ax.bar(labels, actino2, width, label='Actinobacteria', color=['red'])
        ax.bar(labels, thermo, width, label='Thermoleophilia', color=['purple'])
        ax.bar(labels, acidimi, width, label='Acidimicrobiia', color=['blue'])
        ax.bar(labels, rubro, width, label='Rubrobacteria', color=['green'])
        ax.bar(labels, corio, width, label='Coriobacteriia', color=['blue'])
        ax.bar(labels, clost, width, label='Clostridia', color=['yellow'])
        ax.bar(labels, bacil, width, label='Bacilli', color=['orange'])
        ax.bar(labels, erysi, width, label='Erysipelotrichia', color=['black'])
        ax.bar(labels, negati, width, label='Negativicutes', color=['pink'])
        ax.bar(labels, anaero, width, label='Anaerolineae', color=['gray'])
        ax.bar(labels, chrolo2, width, label='Chloroflexia', color=['red'])
        ax.bar(labels, molli, width, label='Mollicutes', color=['purple'])
        ax.bar(labels, chitino, width, label='Chitinophagia', color=['blue'])
        ax.bar(labels, flavo, width, label='Flavobacteriia', color=['green'])
        ax.bar(labels, cytopha, width, label='Cytophagia', color=['blue'])
        ax.bar(labels, sphingo, width, label='Sphingobacteriia', color=['yellow'])
        ax.bar(labels, sapro, width, label='Saprospiria', color=['orange'])
        ax.bar(labels, gemmati2, width, label='Gemmatimonadetes', color=['gray'])
        ax.bar(labels, solibac, width, label='Solibacteres', color=['red'])
        ax.bar(labels, acidob2, width, label='Acidobacteriia', color=['purple'])
        ax.bar(labels, blast, width, label='Blastocatellia', color=['blue'])
        ax.bar(labels, nitros, width, label='Nitrospira', color=['green'])
        ax.bar(labels, defer2, width, label='Deferribacteres', color=['blue'])

        ax.set_ylabel('Signifiance')
        ax.set_title('Sample 1')
        ax.legend()

        plt.show()

    elif menu == '4':
        labels = ['Sample 1']
        rhizo = float(a[6])
        rhodo = float(a[56])
        sphingo2 = float(a[71])
        caulobac = float(a[81])
        rhodo2 = float(a[88])
        myxococ = float(a[94])
        desulfuromonadales = float(a[117])
        desulfubacterales = float(a[120])
        syntrophobac = float(a[132])
        desulfarculates = float(a[137])
        campylobact = float(a[143])
        burkholderial = float(a[149])
        nitrosomona = float(a[172])
        xantho = float(a[185])
        nevskiales = float(a[194])
        oceanospi = float(a[198])
        pseudomonadales = float(a[201])
        cellvibrio = float(a[204])
        thiotricha = float(a[208])
        enterobact = float(a[213])
        bdellovibrio = float(a[218])
        acidithobacilalles = float(a[224])
        propionibacter = float(a[230])
        micrococcales = float(a[237])
        micromonos = float(a[243])
        nakamure = float(a[245])
        corynebac = float(a[251])
        pseudomono = float(a[254])
        streptomyceta = float(a[259])
        solirubro = float(a[263])
        acidimicrobiales = float(a[269])
        rubrobacterales = float(a[275])
        coribacteriales = float(a[281])
        clostridiales = float(a[285])
        bacilalles = float(a[305])
        lactobacilalles = float(a[313])
        erysipelotrichales = float(a[318])
        selemonodales = float(a[323])
        anaerolinedales = float(a[328])
        chroloflexales = float(a[331])
        mycoplasma = float(a[337])
        chitinophagales = float(a[348])
        flavobacteriales = float(a[364])
        bacteriodet = float(a[376])
        cytophagales = float(a[383])
        sphingobacteriales = float(a[388])
        saprospirales = float(a[392])
        gemmatimonadales = float(a[399])
        solibacterales = float(a[407])
        acidobacterales = float(a[413])
        nitrospirales = float(a[434])
        deferribacterales = float(a[439])
        width = 2.0

        fig, ax = plt.subplots()

        ax.bar(labels, rhizo, width, label='Rhizobiales', color=['green'])
        ax.bar(labels, rhodo2, width, label='Rhodospirillales', color=['blue'])
        ax.bar(labels, sphingo2, width, label='Sphingomonadales', color=['yellow'])
        ax.bar(labels, caulobac, width, label='Caulobacterales', color=['orange'])
        ax.bar(labels, rhodo2, width, label='Rhodobacterales', color=['black'])
        ax.bar(labels, myxococ, width, label='Myxococcales', color=['pink'])
        ax.bar(labels, desulfuromonadales, width, label='Desulfuromonadales', color=['gray'])
        ax.bar(labels, desulfubacterales, width, label='Desulfobacterales', color=['red'])
        ax.bar(labels, syntrophobac, width, label='Syntrophobacterales', color=['purple'])
        ax.bar(labels, desulfarculates, width, label='Desulfarculales', color=['blue'])
        ax.bar(labels, campylobact, width, label='Campylobacterales', color=['green'])
        ax.bar(labels, burkholderial, width, label='Burkholderiales', color=['blue'])
        ax.bar(labels, nitrosomona, width, label='Nitrosomonadales', color=['yellow'])
        ax.bar(labels, xantho, width, label='Xanthomonadales', color=['orange'])
        ax.bar(labels, nevskiales, width, label='Nevskiales', color=['black'])
        ax.bar(labels, oceanospi, width, label='Oceanospirillales', color=['pink'])
        ax.bar(labels, pseudomonadales, width, label='Pseudomonadales', color=['gray'])
        ax.bar(labels, cellvibrio, width, label='Cellvibrionales', color=['red'])
        ax.bar(labels, thiotricha, width, label='Thiotrichales', color=['purple'])
        ax.bar(labels, enterobact, width, label='Enterobacterales', color=['blue'])
        ax.bar(labels, bdellovibrio, width, label='Bdellovibrionales', color=['green'])
        ax.bar(labels, acidithobacilalles, width, label='Acidithiobacillales', color=['blue'])
        ax.bar(labels, propionibacter, width, label='Propionibacteriales', color=['yellow'])
        ax.bar(labels, micrococcales, width, label='Micrococcales', color=['orange'])
        ax.bar(labels, micromonos, width, label='Micromonosporales', color=['gray'])
        ax.bar(labels, nakamure, width, label='Nakamurellales', color=['red'])
        ax.bar(labels, corynebac, width, label='Corynebacteriales', color=['purple'])
        ax.bar(labels, pseudomono, width, label='Pseudonocardiales', color=['blue'])
        ax.bar(labels, streptomyceta, width, label='Streptomycetales', color=['green'])
        ax.bar(labels, solibacterales, width, label='Solirubrobacterales', color=['blue'])
        ax.bar(labels, acidimicrobiales, width, label='Acidimicrobiales', color=['blue'])
        ax.bar(labels, rubrobacterales, width, label='Rubrobacterales', color=['green'])
        ax.bar(labels, coribacteriales, width, label='Coriobacteriales', color=['blue'])
        ax.bar(labels, clostridiales, width, label='Clostridiales', color=['yellow'])
        ax.bar(labels, bacilalles, width, label='Bacillales', color=['orange'])
        ax.bar(labels, lactobacilalles, width, label='Lactobacillales', color=['black'])
        ax.bar(labels, erysipelotrichales, width, label='Erysipelotrichales', color=['pink'])
        ax.bar(labels, selemonodales, width, label='Selenomonadales', color=['gray'])
        ax.bar(labels, anaerolinedales, width, label='Anaerolineales', color=['red'])
        ax.bar(labels, chroloflexales, width, label='Chloroflexales', color=['purple'])
        ax.bar(labels, mycoplasma, width, label='Mycoplasmatales', color=['blue'])
        ax.bar(labels, chitinophagales, width, label='Chitinophagales', color=['green'])
        ax.bar(labels, flavobacteriales, width, label='Flavobacteriales', color=['blue'])
        ax.bar(labels, bacteriodet, width, label='Bacteroidetes Order II. Incertae sedis', color=['yellow'])
        ax.bar(labels, cytophagales, width, label='Cytophagales', color=['orange'])
        ax.bar(labels, sphingobacteriales, width, label='Sphingobacteriales', color=['gray'])
        ax.bar(labels, saprospirales, width, label='Saprospirales', color=['red'])
        ax.bar(labels, gemmatimonadales, width, label='Gemmatimonadales', color=['purple'])
        ax.bar(labels, solibacterales, width, label='Solibacterales', color=['blue'])
        ax.bar(labels, acidobacterales, width, label='Acidobacteriales', color=['green'])
        ax.bar(labels, nitrospirales, width, label='Nitrospirales', color=['blue'])
        ax.bar(labels, deferribacterales, width, label='Deferribacterales', color=['purple'])
        ax.set_ylabel('Signifiance')
        ax.set_title('Sample 1')
        ax.legend()

        plt.show()

    elif menu == '5':
        labels = ['Sample 1']
        bradyrhizo = float(a[7])
        hyphomicro = float(a[13])
        phyllobacter = float(a[26])
        xanthobacter = float(a[36])
        rhizobiac = float(a[43])
        beijerinck = float(a[47])
        methylo = float(a[52])
        chelatoco = float(a[54])
        acetobacter = float(a[57])
        rhodospirill = float(a[60])
        sphingomona = float(a[72])
        erythobacter = float(a[79])
        caulobacter = float(a[82])
        rhodobacter = float(a[89])
        polyangi = float(a[96])
        sandarci = float(a[101])
        archagi = float(a[105])
        anaeromy = float(a[108])
        myxococea = float(a[110])
        koflerri = float(a[113])
        geobacter = float(a[118])
        desulfobacter = float(a[121])
        desulfobaceae = float(a[128])
        syntrophaceae = float(a[133])
        desulfarculaceae = float(a[138])
        helicobacter = float(a[144])
        comamonada = float(a[162])
        burkholderiaceae = float(a[170])
        sterolibacter = float(a[173])
        nitrosomonadaceae = float(a[177])
        xanthomonadaceae = float(a[186])
        rhodanobacter = float(a[190])
        sinobacter = float(a[195])
        halomona = float(a[199])
        pseudomonadace = float(a[202])
        haliece = float(a[205])
        francisel = float(a[209])
        erwini = float(a[214])
        bdllovibrinaceae = float(a[219])
        acidithceace = float(a[225])
        nocardioid = float(a[231])
        microbacter = float(a[238])
        micrococaeae = float(a[241])
        cellulomonada = float(a[242])
        micromonosporadeceae = float(a[244])
        nakamurellaceae = float(a[246])
        mycobactericeae = float(a[252])
        pseudocardia = float(a[255])
        streptomycetaceae = float(a[260])
        conexibacteraceae = float(a[264])
        acidimicrobicae = float(a[270])
        rubrobacterceae = float(a[276])
        atopobiaceae = float(a[282])
        clostridicae = float(a[293])
        peptococcae = float(a[300])
        syntrophoma = float(a[306])
        bacillaceae = float(a[308])
        paenibacilla = float(a[310])
        alicyclobacilla = float(a[314])
        carnobacteriaceae = float(a[319])
        erysipelotrichace = float(a[324])
        selemononada = float(a[329])
        anaerolineaceae = float(a[333])
        roseiflexace = float(a[349])
        mycoplasmataceae = float(a[365])
        chitinophagaceae = float(a[377])
        flavobactercae = float(a[384])
        rhodothermaceae = float(a[389])
        hymenobactercae = float(a[393])
        sphingobactercae = float(a[400])
        haliscomonobacter = float(a[408])
        gemmatimonadacae = float(a[414])
        solibactercae = float(a[435])
        acidobactercea = float(a[440])
        nitrospriracea = float(a[435])
        defferibactercae = float(a[440])
        width = 2.0

        fig, ax = plt.subplots()

        ax.bar(labels, bradyrhizo, width, label='Bradyrhizobiaceae', color=['green'])
        ax.bar(labels, hyphomicro, width, label='Hyphomicrobiaceae', color=['blue'])
        ax.bar(labels, phyllobacter, width, label='Phyllobacteriaceae', color=['yellow'])
        ax.bar(labels, xanthobacter, width, label='Xanthobacteraceae', color=['orange'])
        ax.bar(labels, rhizobiac, width, label='Rhizobiaceae', color=['black'])
        ax.bar(labels, beijerinck, width, label='Beijerinckiaceae', color=['pink'])
        ax.bar(labels, methylo, width, label='Methylobacteriaceae', color=['gray'])
        ax.bar(labels, chelatoco, width, label='Chelatococcaceae', color=['red'])
        ax.bar(labels, acetobacter, width, label='Acetobacteraceae', color=['purple'])
        ax.bar(labels, rhodospirill, width, label='Rhodospirillaceae', color=['blue'])
        ax.bar(labels, sphingobactercae, width, label='Sphingomonadaceae', color=['green'])
        ax.bar(labels, erythobacter, width, label='Erythrobacteraceae', color=['blue'])
        ax.bar(labels, caulobacter, width, label='Caulobacteraceae', color=['yellow'])
        ax.bar(labels, rhodobacter, width, label='Rhodobacteraceae', color=['orange'])
        ax.bar(labels, polyangi, width, label='Polyangiaceae', color=['black'])
        ax.bar(labels, sandarci, width, label='Sandaracinaceae', color=['pink'])
        ax.bar(labels, archagi, width, label='Archangiaceae', color=['gray'])
        ax.bar(labels, anaeromy, width, label='Anaeromyxobacteraceae', color=['red'])
        ax.bar(labels, myxococea, width, label='Myxococcaceae', color=['purple'])
        ax.bar(labels, koflerri, width, label='Kofleriaceae', color=['blue'])
        ax.bar(labels, geobacter, width, label='Geobacteraceae', color=['green'])
        ax.bar(labels, desulfobacter, width, label='Desulfobacteraceae', color=['blue'])
        ax.bar(labels, desulfobaceae, width, label='Desulfobulbaceae', color=['yellow'])
        ax.bar(labels, syntrophaceae, width, label='Syntrophaceae', color=['orange'])
        ax.bar(labels, desulfobaceae, width, label='Desulfarculaceae', color=['gray'])
        ax.bar(labels, helicobacter, width, label='Helicobacteraceae', color=['red'])
        ax.bar(labels, comamonada, width, label='Comamonadaceae', color=['purple'])
        ax.bar(labels, burkholderiaceae, width, label='Burkholderiaceae', color=['blue'])
        ax.bar(labels, sterolibacter, width, label='Sterolibacteriaceae', color=['green'])
        ax.bar(labels, nitrosomonadaceae, width, label='Nitrosomonadaceae', color=['blue'])
        ax.bar(labels, xanthomonadaceae, width, label='Xanthomonadaceae', color=['blue'])
        ax.bar(labels, rhodanobacter, width, label='Rhodanobacteraceae', color=['green'])
        ax.bar(labels, sinobacter, width, label='Sinobacteraceae', color=['blue'])
        ax.bar(labels, halomona, width, label='Halomonadaceae', color=['yellow'])
        ax.bar(labels, pseudomonadace, width, label='Pseudomonadaceae', color=['orange'])
        ax.bar(labels, haliece, width, label='Halieaceae', color=['black'])
        ax.bar(labels, francisel, width, label='Francisellaceae', color=['pink'])
        ax.bar(labels, erwini, width, label='Erwiniaceae', color=['gray'])
        ax.bar(labels, bdllovibrinaceae, width, label='Bdellovibrionaceae', color=['red'])
        ax.bar(labels, acidithceace, width, label='Acidithiobacillaceae', color=['purple'])
        ax.bar(labels, nocardioid, width, label='Nocardioidaceae', color=['blue'])
        ax.bar(labels, microbacter, width, label='Microbacteriaceae', color=['green'])
        ax.bar(labels, micrococaeae, width, label='Micrococcaceae', color=['blue'])
        ax.bar(labels, cellulomonada, width, label='Cellulomonadaceae', color=['yellow'])
        ax.bar(labels, micromonosporadeceae, width, label='Micromonosporaceae', color=['orange'])
        ax.bar(labels, nakamurellaceae, width, label='Nakamurellaceae', color=['gray'])
        ax.bar(labels, mycobactericeae, width, label='Mycobacteriaceae', color=['red'])
        ax.bar(labels, pseudocardia, width, label='Pseudonocardiaceae', color=['purple'])
        ax.bar(labels, streptomycetaceae, width, label='Streptomycetaceae', color=['blue'])
        ax.bar(labels, conexibacteraceae, width, label='Conexibacteraceae', color=['green'])
        ax.bar(labels, acidimicrobicae, width, label='Acidimicrobiaceae', color=['blue'])
        ax.bar(labels, rubrobacterceae, width, label='Rubrobacteraceae', color=['purple'])
        ax.bar(labels, atopobiaceae, width, label='Atopobiaceae', color=['blue'])
        ax.bar(labels, clostridicae, width, label='Clostridiaceae', color=['green'])
        ax.bar(labels, peptococcae, width, label='Peptococcaceae', color=['blue'])
        ax.bar(labels, syntrophaceae, width, label='Syntrophomonadaceae', color=['yellow'])
        ax.bar(labels, bacillaceae, width, label='Bacillaceae', color=['orange'])
        ax.bar(labels, paenibacilla, width, label='Paenibacillaceae', color=['black'])
        ax.bar(labels, alicyclobacilla, width, label='Alicyclobacillaceae', color=['pink'])
        ax.bar(labels, carnobacteriaceae, width, label='Carnobacteriaceae', color=['gray'])
        ax.bar(labels, erysipelotrichace, width, label='Erysipelotrichaceae', color=['red'])
        ax.bar(labels, selemononada, width, label='Selenomonadaceae', color=['purple'])
        ax.bar(labels, anaerolineaceae, width, label='Anaerolineaceae', color=['blue'])
        ax.bar(labels, roseiflexace, width, label='Roseiflexaceae', color=['green'])
        ax.bar(labels, mycoplasmataceae, width, label='Mycoplasmataceae', color=['blue'])
        ax.bar(labels, chitinophagaceae, width, label='Chitinophagaceae', color=['yellow'])
        ax.bar(labels, flavobactercae, width, label='Flavobacteriaceae', color=['orange'])
        ax.bar(labels, rhodothermaceae, width, label='Rhodothermaceae', color=['gray'])
        ax.bar(labels, hymenobactercae, width, label='Hymenobacteraceae', color=['red'])
        ax.bar(labels, sphingobactercae, width, label='Sphingobacteriaceae', color=['purple'])
        ax.bar(labels, haliscomonobacter, width, label='Haliscomenobacteraceae', color=['blue'])
        ax.bar(labels, gemmatimonadacae, width, label='Gemmatimonadaceae', color=['green'])
        ax.bar(labels, solibactercae, width, label='Solibacteraceae', color=['blue'])
        ax.bar(labels, acidobactercea, width, label='Acidobacteriaceae', color=['purple'])
        ax.bar(labels, nitrospriracea, width, label='Nitrospiraceae', color=['blue'])
        ax.bar(labels, defferibactercae, width, label='Deferribacteraceae', color=['red'])

        ax.set_ylabel('Signifiance')
        ax.set_title('Sample 1')
        ax.legend()

        plt.show()

    # Volta a nova maneira de preencher as variaveis.

    elif menu == '6':
        labels = ['Sample 1']
        g8 = float(a[8])
        g11 = float(a[11])
        g14 = float(a[14])
        g17 = float(a[17])
        g19 = float(a[19])
        g22 = float(a[22])
        g24 = float(a[24])
        g27 = float(a[27])
        g29 = float(a[29])
        g32 = float(a[32])
        g34 = float(a[34])
        g37 = float(a[37])
        g40 = float(a[40])
        g44 = float(a[44])
        g48 = float(a[48])
        g53 = float(a[53])
        g55 = float(a[55])
        g58 = float(a[58])
        g59 = float(a[59])
        g61 = float(a[61])
        g65 = float(a[65])
        g68 = float(a[68])
        g73 = float(a[73])
        g75 = float(a[75])
        g77 = float(a[77])
        g78 = float(a[78])
        g80 = float(a[80])
        g83 = float(a[83])
        g85 = float(a[85])
        g90 = float(a[90])
        g97 = float(a[97])
        g99 = float(a[99])
        g102 = float(a[102])
        g106 = float(a[106])
        g109 = float(a[109])
        g111 = float(a[111])
        g114 = float(a[114])
        g119 = float(a[119])
        g122 = float(a[122])
        g125 = float(a[125])
        g129 = float(a[129])
        g134 = float(a[134])
        g139 = float(a[139])
        g145 = float(a[145])
        g152 = float(a[152])
        g155 = float(a[155])
        g158 = float(a[158])
        g160 = float(a[160])
        g163 = float(a[163])
        g166 = float(a[166])
        g168 = float(a[168])
        g171 = float(a[171])
        g174 = float(a[174])
        g178 = float(a[178])
        g187 = float(a[187])
        g191 = float(a[191])
        g196 = float(a[196])
        g200 = float(a[200])
        g203 = float(a[203])
        g206 = float(a[206])
        g211 = float(a[210])
        g215 = float(a[215])
        g220 = float(a[220])
        g226 = float(a[226])
        g232 = float(a[232])
        g247 = float(a[247])
        g253 = float(a[253])
        g256 = float(a[256])
        g261 = float(a[261])
        g271 = float(a[271])
        g277 = float(a[277])
        g287 = float(a[287])
        g290 = float(a[290])
        g294 = float(a[294])
        g298 = float(a[298])
        g301 = float(a[301])
        g307 = float(a[307])
        g309 = float(a[309])
        g311 = float(a[311])
        g315 = float(a[315])
        g320 = float(a[320])
        g325 = float(a[325])
        g334 = float(a[334])
        g339 = float(a[339])
        g341 = float(a[341])
        g350 = float(a[350])
        g352 = float(a[352])
        g356 = float(a[356])
        g358 = float(a[358])
        g360 = float(a[360])
        g366 = float(a[366])
        g368 = float(a[368])
        g370 = float(a[370])
        g374 = float(a[374])
        g378 = float(a[378])
        g385 = float(a[385])
        g390 = float(a[390])
        g394 = float(a[394])
        g401 = float(a[401])
        g409 = float(a[409])
        g415 = float(a[415])
        g418 = float(a[418])
        g422 = float(a[422])
        g425 = float(a[425])
        g429 = float(a[429])
        g436 = float(a[436])
        g441 = float(a[441])
        width = 2.0

        fig, ax = plt.subplots()

        ax.bar(labels, g8, width, label=str(b[8]), color=['green'])
        ax.bar(labels, g11, width, label=str(b[11]), color=['blue'])
        ax.bar(labels, g14, width, label=str(b[14]), color=['yellow'])
        ax.bar(labels, g17, width, label=str(b[17]), color=['orange'])
        ax.bar(labels, g19, width, label=str(b[19]), color=['black'])
        ax.bar(labels, g22, width, label=str(b[22]), color=['pink'])
        ax.bar(labels, g24, width, label=str(b[24]), color=['gray'])
        ax.bar(labels, g27, width, label=str(b[27]), color=['red'])
        ax.bar(labels, g29, width, label=str(b[29]), color=['purple'])
        ax.bar(labels, g32, width, label=str(b[32]), color=['blue'])
        ax.bar(labels, g34, width, label=str(b[34]), color=['green'])
        ax.bar(labels, g37, width, label=str(b[37]), color=['blue'])
        ax.bar(labels, g40, width, label=str(b[40]), color=['yellow'])
        ax.bar(labels, g44, width, label=str(b[44]), color=['orange'])
        ax.bar(labels, g48, width, label=str(b[48]), color=['black'])
        ax.bar(labels, g53, width, label=str(b[53]), color=['pink'])
        ax.bar(labels, g55, width, label=str(b[55]), color=['gray'])
        ax.bar(labels, g58, width, label=str(b[58]), color=['red'])
        ax.bar(labels, g59, width, label=str(b[59]), color=['purple'])
        ax.bar(labels, g61, width, label=str(b[61]), color=['blue'])
        ax.bar(labels, g65, width, label=str(b[65]), color=['green'])
        ax.bar(labels, g68, width, label=str(b[68]), color=['blue'])
        ax.bar(labels, g73, width, label=str(b[73]), color=['yellow'])
        ax.bar(labels, g75, width, label=str(b[75]), color=['orange'])
        ax.bar(labels, g77, width, label=str(b[77]), color=['black'])
        ax.bar(labels, g78, width, label=str(b[78]), color=['pink'])
        ax.bar(labels, g80, width, label=str(b[80]), color=['gray'])
        ax.bar(labels, g83, width, label=str(b[83]), color=['red'])
        ax.bar(labels, g85, width, label=str(b[85]), color=['purple'])
        ax.bar(labels, g90, width, label=str(b[90]), color=['blue'])
        ax.bar(labels, g97, width, label=str(b[97]), color=['green'])
        ax.bar(labels, g99, width, label=str(b[99]), color=['blue'])
        ax.bar(labels, g102, width, label=str(b[102]), color=['yellow'])
        ax.bar(labels, g106, width, label=str(b[106]), color=['orange'])
        ax.bar(labels, g109, width, label=str(b[109]), color=['black'])
        ax.bar(labels, g111, width, label=str(b[111]), color=['pink'])
        ax.bar(labels, g114, width, label=str(b[114]), color=['gray'])
        ax.bar(labels, g119, width, label=str(b[119]), color=['red'])
        ax.bar(labels, g122, width, label=str(b[122]), color=['purple'])
        ax.bar(labels, g125, width, label=str(b[125]), color=['blue'])
        ax.bar(labels, g129, width, label=str(b[129]), color=['green'])
        ax.bar(labels, g134, width, label=str(b[134]), color=['blue'])
        ax.bar(labels, g139, width, label=str(b[139]), color=['yellow'])
        ax.bar(labels, g145, width, label=str(b[145]), color=['orange'])
        ax.bar(labels, g152, width, label=str(b[152]), color=['black'])
        ax.bar(labels, g155, width, label=str(b[155]), color=['pink'])
        ax.bar(labels, g158, width, label=str(b[158]), color=['gray'])
        ax.bar(labels, g160, width, label=str(b[160]), color=['red'])
        ax.bar(labels, g163, width, label=str(b[163]), color=['purple'])
        ax.bar(labels, g166, width, label=str(b[166]), color=['blue'])
        ax.bar(labels, g168, width, label=str(b[168]), color=['green'])
        ax.bar(labels, g171, width, label=str(b[171]), color=['blue'])
        ax.bar(labels, g174, width, label=str(b[174]), color=['yellow'])
        ax.bar(labels, g178, width, label=str(b[178]), color=['orange'])
        ax.bar(labels, g187, width, label=str(b[187]), color=['black'])
        ax.bar(labels, g191, width, label=str(b[191]), color=['pink'])
        ax.bar(labels, g196, width, label=str(b[196]), color=['gray'])
        ax.bar(labels, g200, width, label=str(b[200]), color=['red'])
        ax.bar(labels, g203, width, label=str(b[203]), color=['purple'])
        ax.bar(labels, g206, width, label=str(b[206]), color=['blue'])
        ax.bar(labels, g211, width, label=str(b[211]), color=['yellow'])
        ax.bar(labels, g215, width, label=str(b[215]), color=['orange'])
        ax.bar(labels, g220, width, label=str(b[220]), color=['black'])
        ax.bar(labels, g226, width, label=str(b[226]), color=['pink'])
        ax.bar(labels, g232, width, label=str(b[232]), color=['gray'])
        ax.bar(labels, g247, width, label=str(b[247]), color=['red'])
        ax.bar(labels, g253, width, label=str(b[253]), color=['purple'])
        ax.bar(labels, g256, width, label=str(b[256]), color=['blue'])
        ax.bar(labels, g261, width, label=str(b[261]), color=['yellow'])
        ax.bar(labels, g271, width, label=str(b[271]), color=['orange'])
        ax.bar(labels, g277, width, label=str(b[277]), color=['black'])
        ax.bar(labels, g287, width, label=str(b[287]), color=['pink'])
        ax.bar(labels, g290, width, label=str(b[290]), color=['gray'])
        ax.bar(labels, g294, width, label=str(b[294]), color=['red'])
        ax.bar(labels, g298, width, label=str(b[298]), color=['purple'])
        ax.bar(labels, g301, width, label=str(b[301]), color=['blue'])
        ax.bar(labels, g307, width, label=str(b[307]), color=['yellow'])
        ax.bar(labels, g309, width, label=str(b[309]), color=['orange'])
        ax.bar(labels, g311, width, label=str(b[311]), color=['black'])
        ax.bar(labels, g315, width, label=str(b[315]), color=['pink'])
        ax.bar(labels, g320, width, label=str(b[320]), color=['gray'])
        ax.bar(labels, g325, width, label=str(b[325]), color=['red'])
        ax.bar(labels, g334, width, label=str(b[334]), color=['purple'])
        ax.bar(labels, g339, width, label=str(b[339]), color=['blue'])
        ax.bar(labels, g341, width, label=str(b[341]), color=['yellow'])
        ax.bar(labels, g350, width, label=str(b[350]), color=['orange'])
        ax.bar(labels, g352, width, label=str(b[352]), color=['black'])
        ax.bar(labels, g356, width, label=str(b[356]), color=['pink'])
        ax.bar(labels, g358, width, label=str(b[258]), color=['gray'])
        ax.bar(labels, g360, width, label=str(b[360]), color=['red'])
        ax.bar(labels, g366, width, label=str(b[366]), color=['purple'])
        ax.bar(labels, g368, width, label=str(b[368]), color=['blue'])
        ax.bar(labels, g370, width, label=str(b[370]), color=['yellow'])
        ax.bar(labels, g374, width, label=str(b[374]), color=['orange'])
        ax.bar(labels, g378, width, label=str(b[378]), color=['black'])
        ax.bar(labels, g385, width, label=str(b[385]), color=['pink'])
        ax.bar(labels, g390, width, label=str(b[390]), color=['gray'])
        ax.bar(labels, g394, width, label=str(b[394]), color=['red'])
        ax.bar(labels, g401, width, label=str(b[401]), color=['purple'])
        ax.bar(labels, g409, width, label=str(b[409]), color=['blue'])
        ax.bar(labels, g415, width, label=str(b[415]), color=['yellow'])
        ax.bar(labels, g418, width, label=str(b[418]), color=['orange'])
        ax.bar(labels, g422, width, label=str(b[422]), color=['black'])
        ax.bar(labels, g425, width, label=str(b[425]), color=['pink'])
        ax.bar(labels, g429, width, label=str(b[429]), color=['gray'])
        ax.bar(labels, g436, width, label=str(b[436]), color=['red'])
        ax.bar(labels, g441, width, label=str(b[441]), color=['purple'])
        ax.set_ylabel('Signifiance')
        ax.set_title('Sample 1')
        ax.legend()

        plt.show()

    elif menu == '7':
        labels = ['Sample 1']
        s9 = float(a[9])
        s12 = float(a[12])
        s16 = float(a[16])
        s18 = float(a[18])
        s20 = float(a[20])
        s23 = float(a[23])
        s25 = float(a[25])
        s28 = float(a[28])
        s30 = float(a[30])
        s33 = float(a[33])
        s35 = float(a[35])
        s38 = float(a[38])
        s41 = float(a[41])
        s45 = float(a[45])
        s49 = float(a[49])
        s62 = float(a[62])
        s66 = float(a[66])
        s69 = float(a[69])
        s74 = float(a[74])
        s76 = float(a[76])
        s84 = float(a[84])
        s86 = float(a[86])
        s91 = float(a[91])
        s98 = float(a[98])
        s100 = float(a[100])
        s103 = float(a[103])
        s107 = float(a[107])
        s115 = float(a[115])
        s123 = float(a[123])
        s126 = float(a[126])
        s130 = float(a[130])
        s135 = float(a[135])
        s140 = float(a[140])
        s146 = float(a[146])
        s153 = float(a[153])
        s156 = float(a[156])
        s159 = float(a[159])
        s161 = float(a[161])
        s164 = float(a[164])
        s167 = float(a[167])
        s169 = float(a[169])
        s175 = float(a[175])
        s179 = float(a[179])
        s183 = float(a[183])
        s189 = float(a[189])
        s192 = float(a[192])
        s197 = float(a[197])
        s207 = float(a[207])
        s211 = float(a[211])
        s216 = float(a[216])
        s221 = float(a[221])
        s233 = float(a[233])
        s236 = float(a[236])
        s248 = float(a[248])
        s249 = float(a[249])
        s257 = float(a[257])
        s266 = float(a[266])
        s272 = float(a[272])
        s278 = float(a[278])
        s288 = float(a[288])
        s291 = float(a[291])
        s295 = float(a[295])
        s299 = float(a[299])
        s302 = float(a[302])
        s312 = float(a[312])
        s316 = float(a[316])
        s321 = float(a[321])
        s342 = float(a[342])
        s351 = float(a[351])
        s353 = float(a[353])
        s354 = float(a[354])
        s353 = float(a[353])
        s354 = float(a[354])
        s357 = float(a[357])
        s359 = float(a[359])
        s361 = float(a[361])
        s367 = float(a[367])
        s369 = float(a[369])
        s371 = float(a[371])
        s375 = float(a[375])
        s379 = float(a[379])
        s381 = float(a[381])
        s386 = float(a[386])
        s395 = float(a[395])
        s402 = float(a[402])
        s404 = float(a[404])
        s410 = float(a[410])
        s416 = float(a[416])
        s419 = float(a[419])
        s421 = float(a[421])
        s423 = float(a[423])
        s426 = float(a[426])
        s430 = float(a[430])
        s442 = float(a[442])
        width = 2.0

        fig, ax = plt.subplots()

        ax.bar(labels, s9, width, label=str(b[9]), color=['green'])
        ax.bar(labels, s12, width, label=str(b[12]), color=['blue'])
        ax.bar(labels, s16, width, label=str(b[16]), color=['yellow'])
        ax.bar(labels, s18, width, label=str(b[18]), color=['orange'])
        ax.bar(labels, s20, width, label=str(b[20]), color=['black'])
        ax.bar(labels, s23, width, label=str(b[23]), color=['pink'])
        ax.bar(labels, s25, width, label=str(b[25]), color=['gray'])
        ax.bar(labels, s28, width, label=str(b[28]), color=['red'])
        ax.bar(labels, s30, width, label=str(b[30]), color=['purple'])
        ax.bar(labels, s33, width, label=str(b[33]), color=['blue'])
        ax.bar(labels, s35, width, label=str(b[35]), color=['green'])
        ax.bar(labels, s38, width, label=str(b[38]), color=['blue'])
        ax.bar(labels, s41, width, label=str(b[41]), color=['yellow'])
        ax.bar(labels, s45, width, label=str(b[45]), color=['orange'])
        ax.bar(labels, s49, width, label=str(b[49]), color=['pink'])
        ax.bar(labels, s62, width, label=str(b[62]), color=['gray'])
        ax.bar(labels, s66, width, label=str(b[66]), color=['red'])
        ax.bar(labels, s69, width, label=str(b[69]), color=['purple'])
        ax.bar(labels, s74, width, label=str(b[74]), color=['blue'])
        ax.bar(labels, s76, width, label=str(b[76]), color=['green'])
        ax.bar(labels, s84, width, label=str(b[84]), color=['blue'])
        ax.bar(labels, s86, width, label=str(b[86]), color=['yellow'])
        ax.bar(labels, s91, width, label=str(b[91]), color=['orange'])
        ax.bar(labels, s98, width, label=str(b[98]), color=['black'])
        ax.bar(labels, s100, width, label=str(b[100]), color=['pink'])
        ax.bar(labels, s103, width, label=str(b[103]), color=['gray'])
        ax.bar(labels, s107, width, label=str(b[107]), color=['red'])
        ax.bar(labels, s115, width, label=str(b[115]), color=['purple'])
        ax.bar(labels, s123, width, label=str(b[123]), color=['blue'])
        ax.bar(labels, s126, width, label=str(b[126]), color=['green'])
        ax.bar(labels, s130, width, label=str(b[130]), color=['blue'])
        ax.bar(labels, s135, width, label=str(b[135]), color=['yellow'])
        ax.bar(labels, s140, width, label=str(b[140]), color=['orange'])
        ax.bar(labels, s146, width, label=str(b[146]), color=['black'])
        ax.bar(labels, s153, width, label=str(b[153]), color=['pink'])
        ax.bar(labels, s156, width, label=str(b[156]), color=['gray'])
        ax.bar(labels, s159, width, label=str(b[159]), color=['red'])
        ax.bar(labels, s161, width, label=str(b[161]), color=['purple'])
        ax.bar(labels, s164, width, label=str(b[164]), color=['blue'])
        ax.bar(labels, s167, width, label=str(b[167]), color=['green'])
        ax.bar(labels, s169, width, label=str(b[169]), color=['blue'])
        ax.bar(labels, s175, width, label=str(b[175]), color=['yellow'])
        ax.bar(labels, s179, width, label=str(b[179]), color=['orange'])
        ax.bar(labels, s183, width, label=str(b[183]), color=['black'])
        ax.bar(labels, s189, width, label=str(b[189]), color=['pink'])
        ax.bar(labels, s192, width, label=str(b[192]), color=['gray'])
        ax.bar(labels, s197, width, label=str(b[197]), color=['red'])
        ax.bar(labels, s207, width, label=str(b[207]), color=['purple'])
        ax.bar(labels, s211, width, label=str(b[211]), color=['blue'])
        ax.bar(labels, s216, width, label=str(b[216]), color=['green'])
        ax.bar(labels, s221, width, label=str(b[221]), color=['blue'])
        ax.bar(labels, s233, width, label=str(b[233]), color=['yellow'])
        ax.bar(labels, s236, width, label=str(b[236]), color=['orange'])
        ax.bar(labels, s248, width, label=str(b[248]), color=['black'])
        ax.bar(labels, s249, width, label=str(b[249]), color=['pink'])
        ax.bar(labels, s257, width, label=str(b[257]), color=['gray'])
        ax.bar(labels, s266, width, label=str(b[266]), color=['red'])
        ax.bar(labels, s272, width, label=str(b[272]), color=['purple'])
        ax.bar(labels, s278, width, label=str(b[278]), color=['blue'])
        ax.bar(labels, s288, width, label=str(b[288]), color=['yellow'])
        ax.bar(labels, s291, width, label=str(b[291]), color=['orange'])
        ax.bar(labels, s295, width, label=str(b[295]), color=['black'])
        ax.bar(labels, s299, width, label=str(b[299]), color=['pink'])
        ax.bar(labels, s302, width, label=str(b[302]), color=['gray'])
        ax.bar(labels, s312, width, label=str(b[312]), color=['red'])
        ax.bar(labels, s316, width, label=str(b[316]), color=['purple'])
        ax.bar(labels, s321, width, label=str(b[321]), color=['blue'])
        ax.bar(labels, s342, width, label=str(b[342]), color=['yellow'])
        ax.bar(labels, s351, width, label=str(b[351]), color=['orange'])
        ax.bar(labels, s353, width, label=str(b[353]), color=['black'])
        ax.bar(labels, s354, width, label=str(b[354]), color=['pink'])
        ax.bar(labels, s357, width, label=str(b[357]), color=['gray'])
        ax.bar(labels, s359, width, label=str(b[359]), color=['red'])
        ax.bar(labels, s361, width, label=str(b[361]), color=['purple'])
        ax.bar(labels, s367, width, label=str(b[367]), color=['blue'])
        ax.bar(labels, s369, width, label=str(b[369]), color=['yellow'])
        ax.bar(labels, s371, width, label=str(b[371]), color=['orange'])
        ax.bar(labels, s375, width, label=str(b[375]), color=['black'])
        ax.bar(labels, s379, width, label=str(b[379]), color=['pink'])
        ax.bar(labels, s381, width, label=str(b[381]), color=['gray'])
        ax.bar(labels, s386, width, label=str(b[386]), color=['red'])
        ax.bar(labels, s395, width, label=str(b[395]), color=['purple'])
        ax.bar(labels, s402, width, label=str(b[402]), color=['blue'])
        ax.bar(labels, s404, width, label=str(b[404]), color=['yellow'])
        ax.bar(labels, s410, width, label=str(b[410]), color=['orange'])
        ax.bar(labels, s416, width, label=str(b[416]), color=['black'])
        ax.bar(labels, s419, width, label=str(b[419]), color=['pink'])
        ax.bar(labels, s421, width, label=str(b[421]), color=['gray'])
        ax.bar(labels, s423, width, label=str(b[423]), color=['red'])
        ax.bar(labels, s426, width, label=str(b[426]), color=['purple'])
        ax.bar(labels, s430, width, label=str(b[430]), color=['blue'])
        ax.bar(labels, s442, width, label=str(b[442]), color=['yellow'])
        ax.set_ylabel('Signifiance')
        ax.set_title('Sample 1')
        ax.legend()

        plt.show()

    else:
        print('Opção invalida')
